LandDBTest/Models/Value.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandDBTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Value
    {
        public int Id { get; set; }
        public string village { get; set; }
        public Nullable<double> block { get; set; }
        public string county { get; set; }
        public Nullable<double> acreage { get; set; }
        public Nullable<double> fair_value { get; set; }
        public string user { get; set; }
        public string tenure { get; set; }
        public Nullable<System.DateTime> period { get; set; }
        public string currency { get; set; }
        public string development { get; set; }
        public Nullable<double> rateperacre { get; set; }
    }
}

LandDBTest/Controllers/ValuesController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using LandDBTest.Models;
using PagedList;
using Microsoft.AspNet.Identity;
using System.Web.Security;
using System.Collections;
using System.Collections.Generic;

namespace LandDBTest.Controllers
{
    public class ValuesController : Controller
    {
        private landdbContainer db = new landdbContainer();
        String matrix;
       

        // GET: Values
       
      public ActionResult Index()
        {
           return View();
        }
       
        public ActionResult List(int? block, string vill_search, string county, string sortVal, string Filter_Value, int? Page_No)
        {
         
            
            ViewBag.CurrentSortOrder = sortVal;
            ViewBag.blockFilter = block;
            ViewBag.SortingDate = sortVal == "Date_desce" ? "Date_" : "Date_desce";

            if (vill_search != null)
                {

                    Page_No = 1;
                }
                else
                {
                vill_search = Filter_Value;
                
                
                 ViewBag.FilterValue = vill_search;
                ViewBag.blockFilter = block;
                }
          
                ViewBag.FilterValue = vill_search;
     
            var val = from s in db.Values
                      select s;

            if (!String.IsNullOrEmpty(vill_search)|| block!=null)
                {

                val = val.Where(v => v.village.Contains(vill_search.Trim()));
                if (block != null) { val = val.Where(v => v.block.ToString().Contains(block.ToString())); }
               // val=val.Where(v=> v.block.ToString().Contains(block.ToString()));
                }
                switch (sortVal)
                {
                   
                    case "Date_":
                        val = val.OrderBy(stu => stu.period);
                        break;

                case "Date_desce":
                    val = val.OrderByDescending(stu => stu.period);
                    break;

                default:
                        val = val.OrderBy(stu => stu.Id);
                        break;
                }

                int Size_Of_Page = 10;
                int No_Of_Page = (Page_No ?? 1);

            List<string> liststring = new List<string>();

            foreach (var row in val.ToList().Where(x => x.period != null))
            {

                var d8 = Convert.ToDateTime(row.period);
                var d8string = string.Format("new Date({0},{1},{2})", d8.Year, d8.Month, d8.Day);
                string stringRay = string.Format("[{0},{1}]",d8string,row.rateperacre);
               // var joinString = string.Join(",", stringRay);
                // matrix = 
                liststring.Add(stringRay);
            }
          matrix=  string.Join(",", liststring);
                ViewBag.ArrayList = matrix;
            

            
                return View(val.ToPagedList(No_Of_Page, Size_Of_Page));

            }


        [Authorize(Roles = "Admin, CanEdit")]
        // GET: Values/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Value value = db.Values.Find(id);
            if (value == null)
            {
                return HttpNotFound();
            }
            return View(value);
        }

        // GET: Values/Create
        [Authorize(Roles = "Admin, CanEdit")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Values/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,tenure,block,district,county,acreage,use_value,fair_value,village,user")] Value value)
        {
            if (ModelState.IsValid)
            {
                db.Values.Add(value);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(value);
        }

        // GET: Values/Edit/5
        [Authorize(Roles = "Admin, CanEdit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Value value = db.Values.Find(id);
            if (value == null)
            {
                return HttpNotFound();
            }
            return View(value);
        }

        // POST: Values/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, CanEdit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,tenure,block,county,acreage,use_value,fair_value,village,user,period")] Value value)
        {
            if (ModelState.IsValid)
            {
                db.Entry(value).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(value);
        }

        // GET: Values/Delete/5
        [Authorize(Roles = "Admin, CanEdit")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Value value = db.Values.Find(id);
            if (value == null)
            {
                return HttpNotFound();
            }
            return View(value);
        }

        // POST: Values/Delete/5
        [Authorize(Roles = "Admin, CanEdit")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Value value = db.Values.Find(id);
            db.Values.Remove(value);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [AllowAnonymous]
        public JsonResult AutoCompleteVillage(string term)
        {
            var result = (from r in db.Values
                          where r.village.ToLower().StartsWith(term)
                          select new { r.village }).Distinct().Take(8);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ReportWithPivot(int? block, string vill_search)
        {
            if(block!=null && !string.IsNullOrEmpty(vill_search))
            {
                var val = from s in db.Values
                          select s;
                val = val.Where(s => s.village.Contains(vill_search) && s.block.ToString().Contains(block.ToString())&& s.period!=null);

                return View(val.ToList());
            }
            else
            {
              return  View();
            }
            
        }
    }
}

LandDBTest/Views/Values/Create.cshtml
@model LandDBTest.Models.Value

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Value</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.tenure, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tenure, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tenure, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.block, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.block, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.block, "", new { @class = "text-danger" })
            </div>
        </div>

      

        <div class="form-group">
            @Html.LabelFor(model => model.county, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.county, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.county, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.acreage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.acreage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.acreage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.period, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.period.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.period, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fair_value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fair_value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fair_value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.village, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.village, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.village, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.user, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LandDBTest/Views/Values/Delete.cshtml
@model LandDBTest.Models.Value

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Value</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tenure)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenure)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.block)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.block)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.county)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.county)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.acreage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.acreage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.period)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.period)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fair_value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fair_value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.village)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.village)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LandDBTest/Views/Values/Details.cshtml
@model LandDBTest.Models.Value

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Value</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           Tenure
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenure)
        </dd>
        <dt>
         Village
        </dt>

        <dd>
            @Html.DisplayFor(model => model.village)
        </dd>

        <dt>
           Block
        </dt>

        <dd>
            @Html.DisplayFor(model => model.block)
        </dd>

       

        <dt>
       County
        </dt>

        <dd>
            @Html.DisplayFor(model => model.county)
        </dd>
        <dt>
            Acreage
        </dt>

        <dd>
            @Html.DisplayFor(model => model.acreage)
        </dd>
        <dt>
           User
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user)
        </dd>

        <dt>
          Use Value
        </dt>

        

        <dt>
            Current Fair Value
        </dt>

        <dd>
           @string.Format("{0:#,##0}", Model.fair_value)
        </dd>

        <dt>
           Period
        </dt>

        <dd>
            @Html.DisplayFor(model => model.period)
        </dd>

    

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LandDBTest/Views/Values/Index.cshtml
@model LandDBTest.Models.Value

@{
    ViewBag.Title = "Index";
}
@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    $(document).ready(function () {
        $('#find').click(function () {
            var vilSearch = $('#vill_search').val();
            var blockSearch = $('#block').val();
            $('#err').remove();
            $('#err2').remove();
            if (vilSearch == "") {
                $('#vill_search').after("<p id='err' style='color:red;'></p>");
                $('#err').html("* Fill this field first").show().fadeOut(2500);
                $('#block').after("<p id='err2' style='color:red;'></p>");
                $('#err2').html("* then this field next").show().delay(1500).fadeOut(1500);
                return false;
            }

        });
        $('#block').keypress(function (e) {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                $('#err2').html("Digits Only").show().fadeOut("slow");

                return false;
            }
        });

        $("#vill_search").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "/Values/AutoCompleteVillage",
                    type: "POST",
                    dataType: "json",
                    data: { term: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.village, value: item.village };
                        }))
                    }
                })

            },
            messages: {
                noResults: ""
            }
        });

    });
</script>

<div class="jumbotron vertical-center">
    <div class="container text-center">
        <div class="row">
          
            <!-- Trigger the modal with a button -->
            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Click here for demo</button>

            <!-- Modal -->
            <div id="myModal" class="modal fade" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Demonstration</h4>
                        </div>
                        <div class="modal-body">
                            <ul class="nav nav-tabs">
                                <li class="active"><a data-toggle="tab" href="#mailo">Mailo</a></li>
                                <li><a data-toggle="tab" href="#freehold">Freehold</a></li>
                                <li><a data-toggle="tab" href="#leasehold">Leasehold</a></li>                               
                            </ul>
                            <div class="tab-content">
                                <div id="mailo" class="tab-pane fade in active">
                                   <h4>Insert Village and  block as shown below</h4>
                                    <img src="~/Pictures/pic 01.jpg" class="img-responsive" />
                                </div>
                                <div id="freehold" class="tab-pane fade">
                                    <h4>Insert Village and  block as shown below</h4>
                                    <img src="~/Pictures/pic 03.jpg" class="img-responsive" />
                                </div>
                                <div id="leasehold" class="tab-pane fade">
                                    <h4>Insert Village and  block as shown below</h4>
                                    <img src="~/Pictures/pic 02.jpg" class="img-responsive" />
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>

                </div>
            </div>
            @*
    <div>
        <div class="col-lg-6">
            <img src="~/Pictures/pic 01.jpg" height="200" style="min-width:50%;" />
        </div>
        <div class="col-lg-6"></div>
        <img src="~/Pictures/pic 02.jpg" height="200" style="min-width:50%;"/>
    </div>
            *@
            <h4 class="text-primary">
                Insert the name of your village and the block number as they appear on the Certificate of Title to view related transactions
            </h4>
                
        </div>
     
            <div class="home">
                @using (Html.BeginForm("List", "Values", FormMethod.Post))
            {
                    <div class="form-inline">

                        <div class="form-group">
                            <label class="control-label col-md-6"> Enter your Village</label>
                            <div class="col-md-6">
                                @Html.TextBox("vill_search", ViewBag.FilterValue as string, new { placeholder = "" })

                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-6">   Block Number:</label>
                            <div class="col-md-6">
                                @Html.TextBox("block", ViewBag.blockFilter as string, new { placeholder = "", @value = 1 })


                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6">
                                <input type="submit" value="Search" id="find" class="btn btn-default" />
                            </div>
                        </div>
                    </div>



                }
          
        </div>
    </div>
</div>

LandDBTest/Views/Values/List.cshtml
@model PagedList.IPagedList<LandDBTest.Models.Value> 
@using PagedList.Mvc
@{
        ViewBag.Title = "List";
    }
@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    $(document).ready(function() {
        $('#find').click(function() {
            var vilSearch = $('#vill_search').val();
            var blockSearch = $('#block').val();
            $('#err').remove();
            $('#err2').remove();
            if (vilSearch == "") {
                $('#vill_search').after("<p id='err' style='color:red;'></p>");
                $('#err').html("* Fill this field first").show().fadeOut(2500);
                $('#block').after("<p id='err2' style='color:red;'></p>");
                $('#err2').html("* then this field next").show().delay(1500).fadeOut(1500);
                return false;
            }
            
        });
        $('#block').keypress(function (e) {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                $('#err2').html("Digits Only").show().fadeOut("slow");
           
                return false;
            }
        });
        
        $("#vill_search").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: "/Values/AutoCompleteVillage",
                    type: "POST",
                    dataType: "json",
                    data: { term: request.term},
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.village, value: item.village };
                        }))
                    }
                })
            },
            messages: {
                noResults:""
            }
        });
    });
</script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
          var data = new google.visualization.DataTable();
          data.addColumn('date', ' Year');         
          data.addColumn('number', ' Rate per acre');          
         
          data.addRows([@Html.Raw(ViewBag.ArrayList)]);


        var options = {
            title: 'Rate per acre for @ViewBag.FilterValue @if (ViewBag.blockFilter != null) { string.Format("block{0}", ViewBag.blockFilter); } ',
            curveType: 'function',
            animation:{
                duration: 1000,
                easing: 'inAndOut',
                startup: true
            },
          legend: { position: 'bottom' }
            };

                var chart = new google.visualization.LineChart(document.getElementById('curve_chart'));

                chart.draw(data, options);
               
      }
</script>


<!--
<div class="jumbotron" style="text-align:center">
    <h2>Uganda Property Reference</h2>
    <h3>Find Out land Values and Future Infrastructure Projects in your Village.</h3>
    <h5>Search for Comparable Values per Village and Block </h5>
</div>

-->
<hr />
<p>
  @*  @Html.ActionLink("Create New", "Create") *@
</p>

@using (Html.BeginForm("List", "Values", FormMethod.Get))
{
    <div class="form-inline">

        <div class="form-group">
            <label class="control-label col-md-6"> Enter your Village</label>
            <div class="col-md-6">
                @Html.TextBox("vill_search", ViewBag.FilterValue as string, new { placeholder = ""})
              
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-6">   Block Number:</label>
            <div class="col-md-6">
                @Html.TextBox("block", ViewBag.blockFilter as string, new { placeholder = "", @value=1})
      

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-6">
                <input type="submit" value="Search" id="find"  class="btn btn-default" />
            </div>
        </div>
    </div>
<hr />

}
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
            @Html.PagedListPager(Model, Page_No => Url.Action("List",
    new { Page_No, sortVal = ViewBag.CurrentSortOrder, Filter_Value = ViewBag.FilterValue,block = ViewBag.blockFilter
    }))


            <table class="table">
                <tr>
                    <th>
                        Village

                    </th>
                    <th>
                        Block
                    </th>
                   
                    <th>
                        County
                    </th>
                    <th>
                        User
                    </th>
                    <th>
                       Development
                    </th>
                    <th>
                        Acreage
                    </th>
                    <th>
                        Current Fair Value
                    </th>
                  
                    <th>
                        Tenure
                    </th>
                    <th>
                        Date
                        @Html.ActionLink(" ", "List", new { sortVal = ViewBag.SortingDate, Filter_Value = ViewBag.FilterValue},new { @class = "glyphicon glyphicon-sort" })
                     
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.village)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.block)
                        </td>
                        
                        <td>
                            @Html.DisplayFor(modelItem => item.county)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.user)

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.development)

                        </td>


                        <td>
                            @Html.DisplayFor(modelItem => item.acreage)
                        </td>
                      
                        <td>
                            @string.Format("{0:#,##0}", item.fair_value) &nbsp;@Html.DisplayFor(modelItem => item.currency)

                        </td>
                        

                        <td>
                            @Html.DisplayFor(modelItem => item.tenure)
                        </td>
                        <td>
                          @if (item.period == null) { } else { @item.period.GetValueOrDefault().ToString("yyyy") }
                           
                        </td>
                        @*     <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                            </td>
                        *@
                    </tr>
                }


            </table>
            <br />
@*
    @Model.ReportWithPivot("table","period", "fair_value", AggregateFunction.Sum, "village", "block")
    @Model.Pivot("period","fairvalue",AggregateFunction.Sum,"village","block")
*@
<div id="curve_chart" style="width: 900px; height: 500px"></div>
        